openapi: 3.1.0
info:
  title: Recipe Book API
  description: A simple (and fictional) API to manage recipes for a Recipe Book.
  version: 1.0.0
servers:
  - url: https://api.recipeBook.com/v1
    description: Main production server
paths:
  /recipes:
    get:
      summary: Get all recipes
      operationId: getRecipes
      responses:
        '200':
          description: A list of recipes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Recipe'
    post:
      summary: Create a new recipe
      operationId: createRecipe
      requestBody:
        description: Recipe to add to the book
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecipeInput'
      responses:
        '201':
          description: Recipe created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
  /recipes/{recipeId}:
    get:
      summary: Get a recipe by ID
      operationId: getRecipeById
      parameters:
        - name: recipeId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A single recipe
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
        '404':
          description: Recipe not found
    put:
      summary: Update an existing recipe by ID
      operationId: updateRecipe
      parameters:
        - name: recipeId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: Updated recipe data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecipeInput'
      responses:
        '200':
          description: Recipe updated successfully
        '404':
          description: Recipe not found
    delete:
      summary: Delete a recipe by ID
      operationId: deleteRecipe
      parameters:
        - name: recipeId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Recipe deleted successfully
        '404':
          description: Recipe not found
components:
  schemas:
    Recipe:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the recipe
        name:
          type: string
          description: Name of the recipe
        ingredients:
          type: array
          description: List of ingredients
          items:
            type: string
        instructions:
          type: string
          description: Cooking instructions for the recipe
        servings:
          type: integer
          description: Number of servings
        prepTime:
          type: integer
          description: Preparation time in minutes
    RecipeInput:
      type: object
      required:
        - name
        - ingredients
        - instructions
      properties:
        name:
          type: string
          description: Name of the recipe
        ingredients:
          type: array
          description: List of ingredients
          items:
            type: string
        instructions:
          type: string
          description: Cooking instructions for the recipe
        servings:
          type: integer
          description: Number of servings
        prepTime:
          type: integer
          description: Preparation time in minutes
