/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { SpeakeasyRecipeBookCore } from "../core.js";
import * as M from "../lib/matchers.js";
import { RequestOptions } from "../lib/sdks.js";
import { pathToFunc } from "../lib/url.js";
import * as custom_components from "../models/custom_components/index.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/custom_errors/httpclienterrors.js";
import * as custom_errors from "../models/custom_errors/index.js";
import { SDKError } from "../models/custom_errors/sdkerror.js";
import { SDKValidationError } from "../models/custom_errors/sdkvalidationerror.js";
import { Result } from "../types/fp.js";

/**
 * Get all recipes
 */
export async function recipesGetAll(
  client: SpeakeasyRecipeBookCore,
  options?: RequestOptions,
): Promise<
  Result<
    Array<custom_components.Recipe>,
    | custom_errors.AuthError
    | SDKError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >
> {
  const path = pathToFunc("/recipes")();

  const headers = new Headers({
    Accept: "application/json",
  });

  const context = {
    operationID: "getRecipes",
    oAuth2Scopes: [],
    securitySource: null,
  };

  const requestRes = client._createRequest(context, {
    method: "GET",
    path: path,
    headers: headers,
    timeoutMs: options?.timeoutMs || client._options.timeoutMs || -1,
  }, options);
  if (!requestRes.ok) {
    return requestRes;
  }
  const req = requestRes.value;

  const doResult = await client._do(req, {
    context,
    errorCodes: ["401", "404", "4XX", "500", "5XX"],
    retryConfig: options?.retries
      || client._options.retryConfig,
    retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
  });
  if (!doResult.ok) {
    return doResult;
  }
  const response = doResult.value;

  const responseFields = {
    HttpMeta: { Response: response, Request: req },
  };

  const [result] = await M.match<
    Array<custom_components.Recipe>,
    | custom_errors.AuthError
    | SDKError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >(
    M.json(200, z.array(custom_components.Recipe$inboundSchema)),
    M.jsonErr(401, custom_errors.AuthError$inboundSchema),
    M.fail([404, "4XX", 500, "5XX"]),
  )(response, { extraFields: responseFields });
  if (!result.ok) {
    return result;
  }

  return result;
}
