/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { recipesCreate } from "../funcs/recipesCreate.js";
import { recipesDelete } from "../funcs/recipesDelete.js";
import { recipesGetAll } from "../funcs/recipesGetAll.js";
import { recipesGetById } from "../funcs/recipesGetById.js";
import { recipesUpdate } from "../funcs/recipesUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Recipes extends ClientSDK {
  /**
   * Get all recipes
   */
  async getAll(
    options?: RequestOptions,
  ): Promise<Array<components.Recipe>> {
    return unwrapAsync(recipesGetAll(
      this,
      options,
    ));
  }

  /**
   * Create a new recipe
   */
  async create(
    request: components.RecipeInput,
    options?: RequestOptions,
  ): Promise<components.Recipe> {
    return unwrapAsync(recipesCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a recipe by ID
   */
  async getById(
    request: operations.GetRecipeByIdRequest,
    options?: RequestOptions,
  ): Promise<components.Recipe> {
    return unwrapAsync(recipesGetById(
      this,
      request,
      options,
    ));
  }

  /**
   * Update an existing recipe by ID
   */
  async update(
    request: operations.UpdateRecipeRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(recipesUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a recipe by ID
   */
  async delete(
    request: operations.DeleteRecipeRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(recipesDelete(
      this,
      request,
      options,
    ));
  }
}
