/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { statusGetRecipeStatus } from "../funcs/statusGetRecipeStatus.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as custom_components from "../models/custom_components/index.js";
import * as custom_operations from "../models/custom_operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Status extends ClientSDK {
  /**
   * Get the status of a recipe
   */
  async getRecipeStatus(
    request: custom_operations.GetRecipeStatusRequest,
    options?: RequestOptions,
  ): Promise<custom_components.RecipeStatus> {
    return unwrapAsync(statusGetRecipeStatus(
      this,
      request,
      options,
    ));
  }
}
