/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type GetRecipeStatusRequest = {
  id: string;
};

/** @internal */
export const GetRecipeStatusRequest$inboundSchema: z.ZodType<
  GetRecipeStatusRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type GetRecipeStatusRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetRecipeStatusRequest$outboundSchema: z.ZodType<
  GetRecipeStatusRequest$Outbound,
  z.ZodTypeDef,
  GetRecipeStatusRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetRecipeStatusRequest$ {
  /** @deprecated use `GetRecipeStatusRequest$inboundSchema` instead. */
  export const inboundSchema = GetRecipeStatusRequest$inboundSchema;
  /** @deprecated use `GetRecipeStatusRequest$outboundSchema` instead. */
  export const outboundSchema = GetRecipeStatusRequest$outboundSchema;
  /** @deprecated use `GetRecipeStatusRequest$Outbound` instead. */
  export type Outbound = GetRecipeStatusRequest$Outbound;
}
