/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  catchUnrecognizedEnum,
  OpenEnum,
  Unrecognized,
} from "../../types/enums.js";

export const RecipeStatus = {
  NotStarted: "not_started",
  InProgress: "in_progress",
  Complete: "complete",
} as const;
export type RecipeStatus = OpenEnum<typeof RecipeStatus>;

/** @internal */
export const RecipeStatus$inboundSchema: z.ZodType<
  RecipeStatus,
  z.ZodTypeDef,
  unknown
> = z
  .union([
    z.nativeEnum(RecipeStatus),
    z.string().transform(catchUnrecognizedEnum),
  ]);

/** @internal */
export const RecipeStatus$outboundSchema: z.ZodType<
  RecipeStatus,
  z.ZodTypeDef,
  RecipeStatus
> = z.union([
  z.nativeEnum(RecipeStatus),
  z.string().and(z.custom<Unrecognized<string>>()),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RecipeStatus$ {
  /** @deprecated use `RecipeStatus$inboundSchema` instead. */
  export const inboundSchema = RecipeStatus$inboundSchema;
  /** @deprecated use `RecipeStatus$outboundSchema` instead. */
  export const outboundSchema = RecipeStatus$outboundSchema;
}
