/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DeleteRecipeRequest = {
  recipeId: string;
};

/** @internal */
export const DeleteRecipeRequest$inboundSchema: z.ZodType<
  DeleteRecipeRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  recipeId: z.string(),
});

/** @internal */
export type DeleteRecipeRequest$Outbound = {
  recipeId: string;
};

/** @internal */
export const DeleteRecipeRequest$outboundSchema: z.ZodType<
  DeleteRecipeRequest$Outbound,
  z.ZodTypeDef,
  DeleteRecipeRequest
> = z.object({
  recipeId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteRecipeRequest$ {
  /** @deprecated use `DeleteRecipeRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteRecipeRequest$inboundSchema;
  /** @deprecated use `DeleteRecipeRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteRecipeRequest$outboundSchema;
  /** @deprecated use `DeleteRecipeRequest$Outbound` instead. */
  export type Outbound = DeleteRecipeRequest$Outbound;
}
