/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as custom_components from "../custom_components/index.js";

export type GetRecipesRequest = {
  page: number;
};

/**
 * A list of recipes
 */
export type GetRecipesRes = {
  resultArray: Array<custom_components.Recipe>;
};

/** @internal */
export const GetRecipesRequest$inboundSchema: z.ZodType<
  GetRecipesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  page: z.number().int(),
});

/** @internal */
export type GetRecipesRequest$Outbound = {
  page: number;
};

/** @internal */
export const GetRecipesRequest$outboundSchema: z.ZodType<
  GetRecipesRequest$Outbound,
  z.ZodTypeDef,
  GetRecipesRequest
> = z.object({
  page: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetRecipesRequest$ {
  /** @deprecated use `GetRecipesRequest$inboundSchema` instead. */
  export const inboundSchema = GetRecipesRequest$inboundSchema;
  /** @deprecated use `GetRecipesRequest$outboundSchema` instead. */
  export const outboundSchema = GetRecipesRequest$outboundSchema;
  /** @deprecated use `GetRecipesRequest$Outbound` instead. */
  export type Outbound = GetRecipesRequest$Outbound;
}

/** @internal */
export const GetRecipesRes$inboundSchema: z.ZodType<
  GetRecipesRes,
  z.ZodTypeDef,
  unknown
> = z.object({
  resultArray: z.array(custom_components.Recipe$inboundSchema),
});

/** @internal */
export type GetRecipesRes$Outbound = {
  resultArray: Array<custom_components.Recipe$Outbound>;
};

/** @internal */
export const GetRecipesRes$outboundSchema: z.ZodType<
  GetRecipesRes$Outbound,
  z.ZodTypeDef,
  GetRecipesRes
> = z.object({
  resultArray: z.array(custom_components.Recipe$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetRecipesRes$ {
  /** @deprecated use `GetRecipesRes$inboundSchema` instead. */
  export const inboundSchema = GetRecipesRes$inboundSchema;
  /** @deprecated use `GetRecipesRes$outboundSchema` instead. */
  export const outboundSchema = GetRecipesRes$outboundSchema;
  /** @deprecated use `GetRecipesRes$Outbound` instead. */
  export type Outbound = GetRecipesRes$Outbound;
}
